"""empty message

Revision ID: 0d2bc2f2c117
Revises: e34d4ed2bdf1
Create Date: 2022-08-23 20:45:27.692466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2bc2f2c117'
down_revision = 'e34d4ed2bdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizacion', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_cotizaciones', 'cotizacion', ['user_id', 'id'])
    op.create_foreign_key(None, 'cotizacion', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.drop_constraint('unique_cotizaciones', 'cotizacion', type_='unique')
    op.drop_column('cotizacion', 'user_id')
    # ### end Alembic commands ###
