"""empty message

Revision ID: 5af018132ab3
Revises: ccaeacbb5b9c
Create Date: 2022-08-27 00:27:57.411184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af018132ab3'
down_revision = 'ccaeacbb5b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('date', sa.String(length=100), nullable=False))
    op.add_column('user_order', sa.Column('service_name', sa.String(length=100), nullable=False))
    op.add_column('user_order', sa.Column('work_link', sa.String(length=250), nullable=False))
    op.drop_column('user_order', 'link')
    op.drop_column('user_order', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_order', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user_order', sa.Column('link', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('user_order', 'work_link')
    op.drop_column('user_order', 'service_name')
    op.drop_column('user_order', 'date')
    # ### end Alembic commands ###
